apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oj-edicode-dashboard
spec:
  ingressClassName: nginx
  rules:
    - host: dashboard.edicode.dev
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: react-dashboard
                port:
                  number: 80
