const data = [
  {
    key: '1',
    type: 'alogrithm',
    title: 'John Brown',
    difficulty: 'easy',
    acceptance: 20,
  },
  {
    key: '2',
    type: 'alogrithm',
    title: 'Jim Green',
    difficulty: 'hard',
    acceptance: 20,
  },
  {
    key: '3',
    type: 'alogrithm',
    title: 'Joe Black',
    difficulty: 'medium',
    acceptance: 20,
  },
  {
    key: '1',
    type: 'alogrithm',
    title: 'John Brown',
    difficulty: 'easy',
    acceptance: 20,
  },
  {
    key: '2',
    type: 'alogrithm',
    title: 'Jim Green',
    difficulty: 'hard',
    acceptance: 20,
  },
  {
    key: '3',
    type: 'alogrithm',
    title: 'Joe Black',
    difficulty: 'medium',
    acceptance: 20,
  },
  {
    key: '1',
    type: 'alogrithm',
    title: 'John Brown',
    difficulty: 'easy',
    acceptance: 20,
  },
  {
    key: '2',
    type: 'alogrithm',
    title: 'Jim Green',
    difficulty: 'hard',
    acceptance: 20,
  },
  {
    key: '3',
    type: 'alogrithm',
    title: 'Joe Black',
    difficulty: 'medium',
    acceptance: 20,
  },
  {
    key: '1',
    type: 'alogrithm',
    title: 'John Brown',
    difficulty: 'easy',
    acceptance: 20,
  },
  {
    key: '2',
    type: 'alogrithm',
    title: 'Jim Green',
    difficulty: 'hard',
    acceptance: 20,
  },
  {
    key: '3',
    type: 'alogrithm',
    title: 'Joe Black',
    difficulty: 'medium',
    acceptance: 20,
  },
  {
    key: '1',
    type: 'alogrithm',
    title: 'John Brown',
    difficulty: 'easy',
    acceptance: 20,
  },
  {
    key: '2',
    type: 'alogrithm',
    title: 'Jim Green',
    difficulty: 'hard',
    acceptance: 20,
  },
  {
    key: '3',
    type: 'alogrithm',
    title: 'Joe Black',
    difficulty: 'medium',
    acceptance: 20,
  },
];

// export const iconsType = {
//   algorithm: AlgorithmLogo,
//   ai: AILogo,
//   bigData: BigDataLogo,
//   all: AllLogo,
//   checklist: ChecklistLogo,
//   database: DatabaseLogo,
//   frontend: FrontendLogo,
//   git: GitLogo,
//   migration: MigrationLogo,
//   uiUx: UiUxLogo,
// };
